# Dockerfile.python
FROM python:3.13-slim

WORKDIR /app

# Copiar apenas os arquivos necessários para instalar dependências primeiro
COPY selecao_simultanea_python/requirements.txt .

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o restante dos arquivos
COPY selecao_simultanea_python/ .

# Comando para executar os testes
CMD ["pytest"]